### ISSUE TITLE
how do i deploy it?? 

### ISSUE THREAD

**Issue by tuhinpal** [awaitlink/qr-worker#1]
i am working on a project thats need a qr code so i found this.. But i tried to install it and it is not working how can i deploy it

**Comment by awaitlink** [comment]
It appears that we're hitting this issue: https://github.com/rustwasm/wasm-pack/issues/886. I've included the workaround from https://github.com/rustwasm/wasm-pack/issues/886#issuecomment-667669802 in https://github.com/u32i64/qr-worker/commit/8ad33838391df2422d9276c8a71a4f82a765598e.

You should now be able to build and deploy this worker successfully.

Additionally, I've added a [Deploy with Workers](https://developers.cloudflare.com/workers/platform/deploy-button) button to the  [README](https://github.com/u32i64/qr-worker#readme) for easier deployment.

@cachecleanerjeet Thank you for the issue, but in the future please include the exact errors you're getting instead of *"it is not working"*. That would've helped me to identify the underlying issue much quicker.

**Comment by tuhinpal** [comment]
Thank You
